version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_OM_URL: "redis://redis:6379"
  redis:
    image: redis/redis-stack
    ports:
      - '6380:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local